# dockerfile-kasm-kali-rolling-desktop
ARG BASE_TAG="1.15.0-rolling"
ARG BASE_IMAGE="core-kali-rolling"
FROM kasmweb/$BASE_IMAGE:$BASE_TAG
USER root

ENV HOME /home/darkmechanic
ENV STARTUPDIR /dockerstartup
WORKDIR $HOME

### Environment config
ENV DEBIAN_FRONTEND=noninteractive \
    SKIP_CLEAN=true \
    KASM_RX_HOME=$STARTUPDIR/kasmrx \
    DONT_PROMPT_WSL_INSTALL="No_Prompt_please" \
    INST_DIR=$STARTUPDIR/install \
    INST_SCRIPTS="/ubuntu/install/kali/install_kali.sh \
                  /ubuntu/install/chromium/install_chromium.sh \
                  /ubuntu/install/firefox/install_firefox.sh \
                  /ubuntu/install/Oh-My-Posh/install_posh.sh \
                  /ubuntu/install/cleanup/cleanup.sh"

# Install sudo if not installed
RUN apt-get update && apt-get install -y sudo

# Create a new user 'darkmechanic' and add to sudo group
RUN useradd -m -s /bin/bash darkmechanic && \
    echo "darkmechanic ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

# Copy install scripts
COPY ./src/ $INST_DIR

# Run installations
RUN \
  for SCRIPT in $INST_SCRIPTS; do \
    bash ${INST_DIR}${SCRIPT} || exit 1; \
  done && \
  $STARTUPDIR/set_user_permission.sh $HOME && \
  rm -f /etc/X11/xinit/Xclients && \
  chown 1000:0 $HOME && \
  mkdir -p /home/darkmechanic && \
  chown -R 1000:0 /home/darkmechanic && \
  rm -Rf ${INST_DIR}

# Userspace Runtime
ENV HOME /home/darkmechanic
WORKDIR $HOME
USER darkmechanic

CMD ["--tail-log"]
